version: '3'

services:
   database:
      image: postgres:16-alpine
      environment:
         POSTGRES_DB: api
         POSTGRES_PASSWORD: password
         POSTGRES_USER: admin
      healthcheck:
         test: ["CMD", "pg_isready -U ${POSTGRES_USER:-api}"]
         timeout: 5s
         retries: 5
         start_period: 60s
      ports:
         - "5432:5432"
      volumes:
         - ./docker/db/data:/var/lib/postgresql/data:rw
